import { useCallback, useMemo, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { ColumnDef } from '@tanstack/react-table'
import { Eye, Sparkles, Trash2 } from 'lucide-react'
import { useModalStore } from '@/app/store'
import { DataTable } from '@/shared/ui/table'
import { Badge } from '@/shared/ui/badge'
import { Button } from '@/shared/ui/button'
import { AdminConfirmModal, toast } from '@/shared/components/common'
import { getApiErrorMessage } from '@/shared/api/http'
import { useAuthStore } from '@/shared/store/auth.store'
import { useCanAccess } from '@/shared/utils/permissions'
import { useFormatDateTime } from '@/shared/datetime'
import {
  deleteAiReport,
  listAiReports,
  type AiReportDto,
  type AiReportStatus,
} from '../api/aiReports.api'
import { openReportStreamingDrawer } from '../utils/openReportStreamingDrawer'

const SECTION_LABELS: Record<string, string> = {
  profile: 'Profile',
  trading_performance: 'Trading',
  open_positions: 'Open',
  closed_trades: 'Closed',
  financial_activity: 'Finance',
  risk_profile: 'Risk',
  kyc: 'KYC',
  engagement: 'Engagement',
  affiliate: 'Affiliate',
  admin_activity: 'Admin',
}

function statusVariant(status: AiReportStatus): 'success' | 'danger' | 'info' | 'warning' | 'neutral' {
  switch (status) {
    case 'completed':
      return 'success'
    case 'failed':
      return 'danger'
    case 'streaming':
      return 'info'
    case 'pending':
      return 'warning'
    default:
      return 'neutral'
  }
}

export interface UserReportsListTabProps {
  subjectUserId: string
  subjectName?: string
  subjectEmail?: string
}

export function UserReportsListTab({
  subjectUserId,
  subjectName,
  subjectEmail,
}: UserReportsListTabProps) {
  const formatDateTime = useFormatDateTime()
  const queryClient = useQueryClient()
  const openModal = useModalStore((s) => s.openModal)
  const closeModal = useModalStore((s) => s.closeModal)
  const currentUser = useAuthStore((s) => s.user)
  const canDelete = useCanAccess('ai_reports:delete')

  const [deleteTarget, setDeleteTarget] = useState<AiReportDto | null>(null)

  const listQuery = useQuery({
    queryKey: ['ai-reports', 'list', subjectUserId],
    queryFn: () => listAiReports({ subjectUserId, limit: 20 }),
    enabled: Boolean(subjectUserId),
  })

  const deleteMutation = useMutation({
    mutationFn: (id: string) => deleteAiReport(id),
    onSuccess: () => {
      toast.success('Report deleted')
      setDeleteTarget(null)
      void queryClient.invalidateQueries({ queryKey: ['ai-reports', 'list', subjectUserId] })
    },
    onError: (e) => toast.error(getApiErrorMessage(e)),
  })

  const resolveGeneratorLabel = useCallback(
    (report: AiReportDto) => {
      if (!report.generatedByUserId) return '—'
      if (currentUser?.id === report.generatedByUserId) {
        return currentUser.email ?? 'You'
      }
      return `${report.generatedByUserId.slice(0, 8)}…`
    },
    [currentUser],
  )

  const handleView = useCallback(
    (report: AiReportDto) => {
      openReportStreamingDrawer(openModal, closeModal, {
        reportId: report.id,
        subjectName,
        subjectEmail,
      })
    },
    [openModal, closeModal, subjectName, subjectEmail],
  )

  const columns = useMemo<ColumnDef<AiReportDto>[]>(
    () => [
      {
        accessorKey: 'createdAt',
        header: 'Created',
        cell: ({ row }) => (
          <span className="text-sm text-slate-300">{formatDateTime(row.original.createdAt)}</span>
        ),
      },
      {
        id: 'generatedBy',
        header: 'Generated by',
        cell: ({ row }) => (
          <span className="text-sm text-slate-300" title={row.original.generatedByUserId ?? undefined}>
            {resolveGeneratorLabel(row.original)}
          </span>
        ),
      },
      {
        id: 'sections',
        header: 'Sections',
        cell: ({ row }) => {
          const sections = row.original.sections ?? []
          return (
            <div className="flex flex-wrap gap-1 max-w-[220px]">
              {sections.map((s) => (
                <span
                  key={s}
                  className="inline-flex rounded-full bg-slate-700/80 px-2 py-0.5 text-[10px] text-slate-200"
                >
                  {SECTION_LABELS[s] ?? s}
                </span>
              ))}
            </div>
          )
        },
      },
      {
        accessorKey: 'tokensOut',
        header: 'Tokens',
        cell: ({ row }) => (
          <span className="text-sm font-mono text-slate-300">
            {row.original.tokensOut != null ? row.original.tokensOut.toLocaleString() : '—'}
          </span>
        ),
      },
      {
        accessorKey: 'status',
        header: 'Status',
        cell: ({ row }) => (
          <Badge variant={statusVariant(row.original.status)} className="capitalize">
            {row.original.status}
          </Badge>
        ),
      },
      {
        id: 'actions',
        header: 'Actions',
        cell: ({ row }) => {
          const report = row.original
          return (
            <div className="flex items-center gap-1">
              <Button
                type="button"
                variant="ghost"
                size="sm"
                title="View report"
                onClick={() => handleView(report)}
              >
                <Eye className="h-4 w-4" />
              </Button>
              {canDelete && (
                <Button
                  type="button"
                  variant="ghost"
                  size="sm"
                  title="Delete report"
                  className="text-red-400 hover:text-red-300"
                  onClick={() => setDeleteTarget(report)}
                >
                  <Trash2 className="h-4 w-4" />
                </Button>
              )}
            </div>
          )
        },
      },
    ],
    [canDelete, handleView, resolveGeneratorLabel, formatDateTime],
  )

  const items = listQuery.data?.items ?? []

  if (listQuery.isLoading) {
    return (
      <div className="flex h-48 items-center justify-center">
        <div className="h-6 w-6 animate-spin rounded-full border-2 border-slate-600 border-t-blue-500" />
        <span className="ml-2 text-sm text-slate-400">Loading reports…</span>
      </div>
    )
  }

  if (listQuery.isError) {
    return (
      <p className="text-sm text-red-400 p-4">{getApiErrorMessage(listQuery.error)}</p>
    )
  }

  if (items.length === 0) {
    return (
      <div className="flex flex-col items-center justify-center gap-3 py-16 px-4 text-center">
        <Sparkles className="h-10 w-10 text-accent/60" />
        <p className="text-sm text-slate-400 max-w-md">
          No reports generated yet. Click &quot;Generate AI Report&quot; in the user details footer (Overview tab) to create one.
        </p>
      </div>
    )
  }

  return (
    <>
      <div className="p-3 sm:p-4">
        <DataTable columns={columns} data={items} />
      </div>

      <AdminConfirmModal
        isOpen={deleteTarget != null}
        onClose={() => setDeleteTarget(null)}
        onConfirm={() => {
          if (deleteTarget) deleteMutation.mutate(deleteTarget.id)
        }}
        title="Delete AI report"
        message="This report will be permanently removed. This cannot be undone."
        confirmText="Delete"
        type="danger"
        isLoading={deleteMutation.isPending}
        loadingLabel="Deleting…"
      />
    </>
  )
}
