-- Migration: Seed admin user
-- This creates the initial admin user for the platform

-- Insert admin user (password: Admin@12345)
-- Password hash is generated using Argon2id
-- This is a placeholder hash - in production, use actual Argon2id hash
INSERT INTO users (
    id,
    email,
    password_hash,
    first_name,
    last_name,
    role,
    status,
    email_verified,
    group_id,
    created_at,
    updated_at
) VALUES (
    '00000000-0000-0000-0000-000000000001',
    'admin@newpt.local',
    '$argon2id$v=19$m=65536,t=3,p=4$YOUR_SALT_HERE$YOUR_HASH_HERE', -- This will be replaced by backend on first run
    'Admin',
    'User',
    'admin',
    'active',
    true,
    NULL, -- Admin doesn't need a group
    NOW(),
    NOW()
)
ON CONFLICT (email) DO NOTHING;

-- Note: The actual password hash should be generated by the backend using Argon2id
-- This migration just creates the user record structure
-- The backend should update the password_hash on first deployment

